# docker-compose.yml.tpl
# Template for Gitea on QNAP. Variables are substituted at runtime by
# qnap/gitea/bootstrap-gitea.sh using sed. Do not edit this file directly.
#
# Variables substituted at runtime:
#   %%DATA_DIR%%      absolute path to gitea/data
#   %%CONFIG_DIR%%    absolute path to gitea/config
#   %%DB_DIR%%        absolute path to gitea/db
#   %%HTTP_PORT%%     host HTTP port  (default 3000)
#   %%SSH_PORT%%      host SSH port   (default 2222)
#   %%DOMAIN%%        public domain or NAS IP
#   %%ROOT_URL%%      full HTTP URL, e.g. http://192.168.1.10:3000

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - GITEA__server__DOMAIN=%%DOMAIN%%
      - GITEA__server__ROOT_URL=%%ROOT_URL%%
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__SSH_DOMAIN=%%DOMAIN%%
      - GITEA__server__SSH_PORT=%%SSH_PORT%%
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea.db
      - GITEA__log__LEVEL=Info
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - %%DATA_DIR%%:/data
      - %%CONFIG_DIR%%:/etc/gitea
      - %%DB_DIR%%:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "%%HTTP_PORT%%:3000"
      - "%%SSH_PORT%%:22"
