# docker-compose.yml.tpl
# Template for Forgejo on QNAP. Variables are substituted at runtime by
# qnap/forgejo/bootstrap-forgejo.sh using sed. Do not edit this file directly.
#
# Variables substituted at runtime:
#   %%DATA_DIR%%      absolute path to forgejo/data
#   %%CONFIG_DIR%%    absolute path to forgejo/config
#   %%HTTP_PORT%%     host HTTP port  (default 3000)
#   %%SSH_PORT%%      host SSH port   (default 2222)
#   %%DOMAIN%%        public domain or NAS IP
#   %%ROOT_URL%%      full HTTP URL, e.g. http://192.168.1.10:3000
#
# Image: codeberg.org/forgejo/forgejo (NOT Docker Hub)
# Forgejo uses FORGEJO__ env prefix (same pattern as Gitea's GITEA__)

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:latest
    container_name: forgejo
    restart: unless-stopped
    environment:
      - FORGEJO__server__DOMAIN=%%DOMAIN%%
      - FORGEJO__server__ROOT_URL=%%ROOT_URL%%
      - FORGEJO__server__HTTP_PORT=3000
      - FORGEJO__server__SSH_DOMAIN=%%DOMAIN%%
      - FORGEJO__server__SSH_PORT=%%SSH_PORT%%
      - FORGEJO__database__DB_TYPE=sqlite3
      - FORGEJO__database__PATH=/data/forgejo.db
      - FORGEJO__log__LEVEL=Info
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - %%DATA_DIR%%:/data
      - %%CONFIG_DIR%%:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "%%HTTP_PORT%%:3000"
      - "%%SSH_PORT%%:22"
